# config/validator/validation.yaml
App\Entity\Profile:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
              fields: ['nationalId']
              ignoreNull: ["phoneNumber"]
    properties:
        nationalId:
            - nationalId: ~